dependencies:
  - python=3.5.3
  - sphinx=1.5.1
  - nose=1.3.7
  - coverage=4.3.4
  - flake8=3.3.0
  - pylint=1.6.4 
  - numpy=1.12.0
  - pip=9.0.1
  - scikit-learn=0.18.1
  - scipy=0.18.1
  - matplotlib
  - pip:
    - pyyaml==3.12
    - tensorflow-gpu==1.0.1
    - nibabel==2.1.0
    - git+https://github.com/vwegmayr/sumatra
    - configparser
    - gitpython
